apiVersion: v1
data:
  CACHE_TTL_BENIGN_SECONDS: "86400"
  CACHE_TTL_MALICIOUS_SECONDS: "900"
  CACHE_TTL_SUSPICIOUS_SECONDS: "3600"
  CONTROL_PLANE_API_TOKEN: ""
  CONTROL_PLANE_BASE: "http://control-plane:8080"
  CONTROL_PLANE_ENABLE_UI: "true"
  CONTROL_PLANE_PORT: "8080"
  DOCKER_COMPOSE_PROFILES: "default"
  FEATURE_ATTACH_MEDIA_VERDICTS: "false"
  GRAFANA_PORT: "3002"
  GSB_API_KEY: ""
  GSB_FALLBACK_LATENCY_MS: "500"
  GSB_REQUEST_TIMEOUT_MS: "5000"
  JWT_SECRET: ""
  LLM_ENABLED: "false"
  METRICS_PORT: "9090"
  NODE_ENV: "development"
  OPENAI_API_KEY: ""
  PHISHTANK_APP_KEY: ""
  PHISHTANK_ENABLED: "false"
  PHISHTANK_TIMEOUT_MS: "5000"
  PHISHTANK_USER_AGENT: "wbscanner-bot/1.0"
  PROMETHEUS_SCRAPE_INTERVAL: "5s"
  RDAP_TIMEOUT_MS: "5000"
  REDIS_URL: "redis://redis:6379/0"
  REVERSE_PROXY_ALLOWED_IPS: "0.0.0.0/0"
  REVERSE_PROXY_PORT: "8088"
  SCAN_CONCURRENCY: "10"
  SCAN_REQUEST_QUEUE: "scan-request"
  SCAN_URLSCAN_QUEUE: "scan-urlscan"
  SCAN_VERDICT_QUEUE: "scan-verdict"
  SESSION_SECRET: ""
  SHORTENER_CACHE_TTL_SECONDS: "86400"
  SQLITE_DB_PATH: "/app/storage/wbscanner.db"
  UNSHORTEN_ENDPOINT: "https://unshorten.me/json/"
  UNSHORTEN_RETRIES: "1"
  UPTIME_KUMA_PORT: "3001"
  URL_EXPANSION_MAX_REDIRECTS: "5"
  URL_EXPANSION_TIMEOUT_MS: "5000"
  URL_MAX_CONTENT_LENGTH: "1048576"
  URLHAUS_ENABLED: "true"
  URLHAUS_TIMEOUT_MS: "5000"
  URLSCAN_API_KEY: ""
  URLSCAN_BASE_URL: "https://urlscan.io"
  URLSCAN_CALLBACK_SECRET: ""
  URLSCAN_CALLBACK_URL: "http://reverse-proxy:8088/urlscan/callback"
  URLSCAN_CONCURRENCY: "2"
  URLSCAN_ENABLED: "true"
  URLSCAN_RESULT_TIMEOUT_MS: "30000"
  URLSCAN_RESULT_TTL_SECONDS: "86400"
  URLSCAN_SUBMIT_TIMEOUT_MS: "10000"
  URLSCAN_TAGS: "wbscanner"
  URLSCAN_UUID_TTL_SECONDS: "86400"
  URLSCAN_VISIBILITY: "private"
  VT_API_KEY: ""
  VT_REQUEST_JITTER_MS: "500"
  VT_REQUEST_TIMEOUT_MS: "8000"
  VT_REQUESTS_PER_MINUTE: "4"
  WA_ALERT_WEBHOOK_URL: ""
  WA_AUTH_CLIENT_ID: "default"
  WA_AUTH_STRATEGY: "remote"
  WA_AUTO_APPROVE_DEFAULT: "true"
  WA_AUTO_APPROVE_RATE_PER_HOUR: "20"
  WA_CONSENT_ON_JOIN: "true"
  WA_GLOBAL_REPLY_RATE_PER_HOUR: "1000"
  WA_GOVERNANCE_ACTIONS_PER_HOUR: "12"
  WA_HEADLESS: "true"
  WA_HEALTH_QUEUE: "wa-health"
  WA_PER_GROUP_HOURLY_LIMIT: "60"
  WA_PER_GROUP_REPLY_COOLDOWN_SECONDS: "60"
  WA_QR_TERMINAL: "true"
  WA_QUIET_HOURS: "22-07"
  WA_REMOTE_AUTH_AUTO_PAIR: "true"
  WA_REMOTE_AUTH_BACKUP_INTERVAL_MS: "300000"
  WA_REMOTE_AUTH_DATA_KEY: ""
  WA_REMOTE_AUTH_DATA_PATH: "./data/remote-session"
  WA_REMOTE_AUTH_DISABLE_QR_FALLBACK: "true"
  WA_REMOTE_AUTH_MAX_RETRIES: "10"
  WA_REMOTE_AUTH_PHONE_NUMBER: ""
  WA_REMOTE_AUTH_PHONE_NUMBERS: ""
  WA_REMOTE_AUTH_RETRY_DELAY_MS: "60000"
  WA_REMOTE_AUTH_SHARED_SECRET: ""
  WA_REMOTE_AUTH_STORE: "redis"
  WA_VERDICT_ACK_MAX_RETRIES: "2"
  WA_VERDICT_ACK_TIMEOUT_SECONDS: "15"
  WA_VERDICT_MEDIA_DIR: ""
  WHOISXML_API_KEY: ""
  WHOISXML_ENABLED: "true"
  WHOISXML_TIMEOUT_MS: "5000"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: control-plane-env
  name: env
