apiVersion: v1
kind: Secret
metadata:
  name: wbscanner-secrets
type: Opaque
data:
  CONTROL_PLANE_API_TOKEN: MGM2MzEyODFiZTUzMjkwNmJhNmFmMzI0YTVlYTYyNmFlYzNkZTI5NGJkM2ViNzFhYTBiMjg3Mjk0MjM0NGZiNw==
  GSB_API_KEY: QUl6YVN5QktqOFJ6aEdkUUo3RUZRcE9VbXZqX1J5RE1uRG8ydFBN
  JWT_SECRET: MjdiZmY4M2ZjYmU4MjRhOGVlNGE4YzAzYmZmYmI2NWUwZDZhZTRhYTU3ZDNiNDEyMGJmYjkyZDkzZmQwNDIzZA==
  OPENAI_API_KEY: ""
  SESSION_SECRET: d1RDVWMrZ1N2TGJ3VDIyMHdpOG4za0lsY0JjS3RHalJaRGk3eHVXYTdCb3FrcFpnSXdRVTV5K3BsSzhLMWppZw==
  URLSCAN_API_KEY: MDE5YTEwZTgtMTA5MS03NGMzLTlmZDctMmNiMDU1MGYzZTlk
  URLSCAN_CALLBACK_SECRET: Y2ZlYWJkODk4ZjkwY2U0ZWE0OTYzODg3ZGI5YmQ3MzQ4NjY0MzBiNzY2MjQ4Y2Q3MWMzNThkODliNGUxYWZmMg==
  VT_API_KEY: MTliOWI2NzQ5YWY2YmM1M2Y2MTNiMjBhYTQ0MDk4Njk0ZDE2NjFjNTg3ODc4Mjk3MjZmY2E5YjAxMWMzYzQxMQ==
  WA_REMOTE_AUTH_DATA_KEY: bTJDZC9KdWd3V2wwUndSbSt5aWZrWUJpTU1Vdm0xanV2bVgyd1ZRNWlzOD0=
  WA_REMOTE_AUTH_SHARED_SECRET: N2VjZWJmNGM1ZTQ0NTk1NzZlNTE5OTA4YTJmMjI1NTM2MWE2NTU5YTVhNWEzMzIxYTgwOTkyZjE4OGI2ZjUyNg==
  WHOISXML_API_KEY: YXRfb3FtTTVUUU5QR3dvNnV1NkFRWUJZM3VTeUNRMjE=
