apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: wa-client
  name: wa-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wa-client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: wa-client
    spec:
      containers:
        - env:
            - name: NODE_OPTIONS
              value: --max-old-space-size=768
            - name: PORT
              value: "3005"
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: wbscanner-secrets
          image: wa-client
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - wget -qO- http://localhost:3005/healthz || exit 1
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          name: wa-client
          ports:
            - containerPort: 3005
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: "1073741824"
            requests:
              cpu: 200m
              memory: "536870912"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - SETGID
                - SETUID
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /app/services/wa-client/data
              name: wa-session
            - mountPath: /app/storage
              name: wa-client-cm1
            - mountPath: /tmp
              name: wa-client-tmpfs0
      restartPolicy: Always
      volumes:
        - name: wa-session
          persistentVolumeClaim:
            claimName: wa-session
        - configMap:
            name: wa-client-cm1
          name: wa-client-cm1
        - emptyDir:
            medium: Memory
          name: wa-client-tmpfs0
