global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'wa-client'
    static_configs:
      - targets: ['host.docker.internal:3006']
        labels:
          service: 'wa-client'
    metrics_path: /metrics
  - job_name: 'scan-orchestrator'
    static_configs:
      - targets: ['host.docker.internal:3003']
        labels:
          service: 'scan-orchestrator'
    metrics_path: /metrics
  - job_name: 'control-plane'
    static_configs:
      - targets: ['host.docker.internal:8087']
        labels:
          service: 'control-plane'
    metrics_path: /metrics
