global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'wa-client'
    static_configs:
      - targets: ['wa-client:3000']
        labels:
          service: 'wa-client'
    metrics_path: /metrics
  - job_name: 'scan-orchestrator'
    static_configs:
      - targets: ['scan-orchestrator:3001']
        labels:
          service: 'scan-orchestrator'
    metrics_path: /metrics
  - job_name: 'control-plane'
    static_configs:
      - targets: ['control-plane:8080']
        labels:
          service: 'control-plane'
    metrics_path: /metrics
